/* eslint-disable global-require */
const images = {
    noPhoto: require('./images/no-photo.jpeg'),
    logo: require('./images/LogoMaisTop.png'),
    logoClean: require('./images/LogoClean.png'),
    logoWhite: require('./images/LogoMaisTopWhite.png'),
    manBottom1: require('./images/ManBottom1.png'),
    manBottom2: require('./images/manBottom2.png'),
    manBottom3: require('./images/manBottom3.png'),
    manTablet: require('./images/manTablet.png'),
    manRight1: require('./images/ManRight1.png'),
    icon1: require('./images/icon1.png'),
    icon2: require('./images/icon2.png'),
    icon3: require('./images/icon3.png'),
    icon4: require('./images/icon4.png'),
    brands: require('./images/BrastempConsul.png'),
    faq: require('./images/faq.png'),
    spreadsheet: require('./images/spreadsheet.png'),
    spreadsheetCalendar: require('./images/spreadsheet-calendar.png'),
    spreadsheetSales: require('./images/spreadsheet-sales.png'),
    spreadsheetEmployees: require('./images/spreadsheet-employees.png'),
    spreadsheetWraning: require('./images/spreadsheet-warning.png'),
    spreadsheetStep1: require('./images/spreadsheet-step-1.png'),
    spreadsheetStep2: require('./images/spreadsheet-step-2.png'),
    spreadsheetStep3: require('./images/spreadsheet-step-3.png'),
    spreadsheetStep4: require('./images/spreadsheet-step-4.png'),
    salesDark1: require('./images/sales-dark-1.png'),
    salesDark2: require('./images/sales-dark-2.png'),
    salesDark3: require('./images/sales-dark-3.png'),
    salesLight1: require('./images/sales-light-1.png'),
    salesLight2: require('./images/sales-light-2.png'),
    salesLight3: require('./images/sales-light-3.png'),
    employeesDark1: require('./images/employees-dark-1.png'),
    employeesDark2: require('./images/employees-dark-2.png'),
    employeesDark3: require('./images/employees-dark-3.png'),
    employeesDark4: require('./images/employees-dark-4.png'),
    employeesDark5: require('./images/employees-dark-5.png'),
    employeesLight1: require('./images/employees-light-1.png'),
    employeesLight2: require('./images/employees-light-2.png'),
    employeesLight3: require('./images/employees-light-3.png'),
    employeesLight4: require('./images/employees-light-4.png'),
    employeesLight5: require('./images/employees-light-5.png'),
    inviteIcon: require('./images/invite-icon.png'),
    aboutInvite1: require('./images/about-invite-1.png'),
    aboutInvite2: require('./images/about-invite-2.png'),
    aboutInvite3: require('./images/about-invite-3.png'),
    aboutInvite4: require('./images/about-invite-4.png'),
    inviteIcon1: require('./images/inivite-icon-1.png'),
    inviteIcon2: require('./images/inivite-icon-2.png'),
    inviteIcon3: require('./images/inivite-icon-3.png'),
    modalError: require('./images/modal-error.png'),
    modalSuccess: require('./images/modal-success.png'),
    updateUser: require('./images/atualiza-dados.png'),
};

export default images;
