const ACTIONSNAME = {
    // Auth
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    GET_SHOP_REQUEST: 'GET_SHOP_REQUEST',
    GET_SHOP_SUCCESS: 'GET_SHOP_SUCCESS',
    GET_SHOP_FAILURE: 'GET_SHOP_FAILURE',

    GET_ACADEMY_REQUEST: 'GET_ACADEMY_REQUEST',
    GET_ACADEMY_SUCCESS: 'GET_ACADEMY_SUCCESS',
    GET_ACADEMY_FAILURE: 'GET_ACADEMY_FAILURE',

    AUTH_RESET: 'AUTH_RESET',

    LOGOUT: 'LOGOUT',

    // New Password
    NEW_PASSWORD_REQUEST: 'NEW_PASSWORD_REQUEST',
    NEW_PASSWORD_SUCCESS: 'NEW_PASSWORD_SUCCESS',
    NEW_PASSWORD_FAILURE: 'NEW_PASSWORD_FAILURE',
    
    // Reset Password
    RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

    RESET_PASSWORD_RESET: 'RESET_PASSWORD_RESET',

    // FirstAccess
    FIRST_ACCESS_RESET: 'FIRST_ACCESS_RESET',

    FIRST_ACCESS_REQUEST: 'FIRST_ACCESS_REQUEST',
    FIRST_ACCESS_SUCCESS: 'FIRST_ACCESS_SUCCESS',
    FIRST_ACCESS_FAILURE: 'FIRST_ACCESS_FAILURE',

    // Signup
    SIGNUP_RESET: 'SIGNUP_RESET',

    PRE_REGISTRATION_REQUEST: 'PRE_REGISTRATION_REQUEST',
    PRE_REGISTRATION_SUCCESS: 'PRE_REGISTRATION_SUCCESS',
    PRE_REGISTRATION_FAILURE: 'PRE_REGISTRATION_FAILURE',

    // SMS
    SMS_RESET: 'SMS_RESET',

    GET_SMS_REQUEST: 'GET_SMS_REQUEST',
    GET_SMS_SUCCESS: 'GET_SMS_SUCCESS',
    GET_SMS_FAILURE: 'GET_SMS_FAILURE',

    GET_SMS_PASSWORD_REQUEST: 'GET_SMS_PASSWORD_REQUEST',
    GET_SMS_PASSWORD_SUCCESS: 'GET_SMS_PASSWORD_SUCCESS',
    GET_SMS_PASSWORD_FAILURE: 'GET_SMS_PASSWORD_FAILURE',

    // User
    USER_RESET: 'USER_RESET',

    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',
    
    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',

    UPDATE_USER_PHONE_REQUEST: 'UPDATE_USER_PHONE_REQUEST',
    UPDATE_USER_PHONE_SUCCESS: 'UPDATE_USER_PHONE_SUCCESS',
    UPDATE_USER_PHONE_FAILURE: 'UPDATE_USER_PHONE_FAILURE',

    // User
    NETWORK_RESET: 'NETWORK_RESET',

    GET_NETWORK_REQUEST: 'GET_NETWORK_REQUEST',
    GET_NETWORK_SUCCESS: 'GET_NETWORK_SUCCESS',
    GET_NETWORK_FAILURE: 'GET_NETWORK_FAILURE',

    // Punctuation
    PONCTUATION_RESET: 'PONCTUATION_RESET',

    GET_PONCTUATION_REQUEST: 'GET_PONCTUATION_REQUEST',
    GET_PONCTUATION_SUCCESS: 'GET_PONCTUATION_SUCCESS',
    GET_PONCTUATION_FAILURE: 'GET_PONCTUATION_FAILURE',

    GET_CREDITS_REQUEST: 'GET_CREDITS_REQUEST',
    GET_CREDITS_SUCCESS: 'GET_CREDITS_SUCCESS',
    GET_CREDITS_FAILURE: 'GET_CREDITS_FAILURE',

    // News
    GET_NEWS_REQUEST: 'GET_NEWS_REQUEST',
    GET_NEWS_SUCCESS: 'GET_NEWS_SUCCESS',
    GET_NEWS_FAILURE: 'GET_NEWS_FAILURE',

    // Products
    PRODUCTS_RESET: 'PRODUCTS_RESET',

    GET_FOCUS_PRODUCTS_REQUEST: 'GET_FOCUS_PRODUCTS_REQUEST',
    GET_FOCUS_PRODUCTS_SUCCESS: 'GET_FOCUS_PRODUCTS_SUCCESS',
    GET_FOCUS_PRODUCTS_FAILURE: 'GET_FOCUS_PRODUCTS_FAILURE',

    GET_ALL_PRODUCTS_REQUEST: 'GET_ALL_PRODUCTS_REQUEST',
    GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_FAILURE: 'GET_ALL_PRODUCTS_FAILURE',

    // Occurrence
    OCCURRENCE_RESET: 'OCCURRENCE_RESET',

    NEW_OCCURRENCE_REQUEST: 'NEW_OCCURRENCE_REQUEST',
    NEW_OCCURRENCE_SUCCESS: 'NEW_OCCURRENCE_SUCCESS',
    NEW_OCCURRENCE_FAILURE: 'NEW_OCCURRENCE_FAILURE',

    GET_OCCURRENCE_REQUEST: 'GET_OCCURRENCE_REQUEST',
    GET_OCCURRENCE_SUCCESS: 'GET_OCCURRENCE_SUCCESS',
    GET_OCCURRENCE_FAILURE: 'GET_OCCURRENCE_FAILURE',

    GET_MSG_OCCURRENCE_REQUEST: 'GET_MSG_OCCURRENCE_REQUEST',
    GET_MSG_OCCURRENCE_SUCCESS: 'GET_MSG_OCCURRENCE_SUCCESS',
    GET_MSG_OCCURRENCE_FAILURE: 'GET_MSG_OCCURRENCE_FAILURE',

    SEND_MSG_OCCURRENCE_REQUEST: 'SEND_MSG_OCCURRENCE_REQUEST',
    SEND_MSG_OCCURRENCE_SUCCESS: 'SEND_MSG_OCCURRENCE_SUCCESS',
    SEND_MSG_OCCURRENCE_FAILURE: 'SEND_MSG_OCCURRENCE_FAILURE',

    // Team
    TEAM_RESET: 'OCCURRENCE_RESET',

    GET_TEAM_USERS_REQUEST: 'GET_TEAM_USERS_REQUEST',
    GET_TEAM_USERS_SUCCESS: 'GET_TEAM_USERS_SUCCESS',
    GET_TEAM_USERS_FAILURE: 'GET_TEAM_USERS_FAILURE',

    GET_TEAM_USERS_DETAIL_REQUEST: 'GET_TEAM_USERS_DETAIL_REQUEST',
    GET_TEAM_USERS_DETAIL_SUCCESS: 'GET_TEAM_USERS_DETAIL_SUCCESS',
    GET_TEAM_USERS_DETAIL_FAILURE: 'GET_TEAM_USERS_DETAIL_FAILURE',

    GET_TEAM_SALES_REQUEST: 'GET_TEAM_SALES_REQUEST',
    GET_TEAM_SALES_SUCCESS: 'GET_TEAM_SALES_SUCCESS',
    GET_TEAM_SALES_FAILURE: 'GET_TEAM_SALES_FAILURE',

    GET_TEAM_SALES_DETAIL_REQUEST: 'GET_TEAM_SALES_DETAIL_REQUEST',
    GET_TEAM_SALES_DETAIL_SUCCESS: 'GET_TEAM_SALES_DETAIL_SUCCESS',
    GET_TEAM_SALES_DETAIL_FAILURE: 'GET_TEAM_SALES_DETAIL_FAILURE',

    GET_TEAM_TRAINING_REQUEST: 'GET_TEAM_TRAINING_REQUEST',
    GET_TEAM_TRAINING_SUCCESS: 'GET_TEAM_TRAINING_SUCCESS',
    GET_TEAM_TRAINING_FAILURE: 'GET_TEAM_TRAINING_FAILURE',

    GET_TEAM_TRAINING_DETAIL_REQUEST: 'GET_TEAM_TRAINING_DETAIL_REQUEST',
    GET_TEAM_TRAINING_DETAIL_SUCCESS: 'GET_TEAM_TRAINING_DETAIL_SUCCESS',
    GET_TEAM_TRAINING_DETAIL_FAILURE: 'GET_TEAM_TRAINING_DETAIL_FAILURE',

    // Sales
    SALES_RESET: 'SALES_RESET',

    GET_SALES_REQUEST: 'GET_SALES_REQUEST',
    GET_SALES_SUCCESS: 'GET_SALES_SUCCESS',
    GET_SALES_FAILURE: 'GET_SALES_FAILURE',

    // Orders
    ORDERS_RESET: 'ORDERS_RESET',

    GET_ORDERS_REQUEST: 'GET_ORDERS_REQUEST',
    GET_ORDERS_SUCCESS: 'GET_ORDERS_SUCCESS',
    GET_ORDERS_FAILURE: 'GET_ORDERS_FAILURE',

    // Campaigns
    CAMPAIGN_RESET: 'ORDERS_RESET',

    GET_CAMPAIGNS_REQUEST: 'GET_CAMPAIGNS_REQUEST',
    GET_CAMPAIGNS_SUCCESS: 'GET_CAMPAIGNS_SUCCESS',
    GET_CAMPAIGNS_FAILURE: 'GET_CAMPAIGNS_FAILURE',
    // Sales File
    SALES_FILE_RESET: 'SALES_FILE_RESET',

    SEND_SALES_FILE_REQUEST: 'SEND_SALES_FILE_REQUEST',
    SEND_SALES_FILE_SUCCESS: 'SEND_SALES_FILE_SUCCESS',
    SEND_SALES_FILE_FAILURE: 'SEND_SALES_FILE_FAILURE',

    GET_SALES_FILE_REQUEST: 'GET_SALES_FILE_REQUEST',
    GET_SALES_FILE_SUCCESS: 'GET_SALES_FILE_SUCCESS',
    GET_SALES_FILE_FAILURE: 'GET_SALES_FILE_FAILURE',

    // Employees File
    EMPLOYEES_FILE_RESET: 'EMPLOYEES_FILE_RESET',

    SEND_EMPLOYEES_FILE_REQUEST: 'SEND_EMPLOYEES_FILE_REQUEST',
    SEND_EMPLOYEES_FILE_SUCCESS: 'SEND_EMPLOYEES_FILE_SUCCESS',
    SEND_EMPLOYEES_FILE_FAILURE: 'SEND_EMPLOYEES_FILE_FAILURE',

    GET_EMPLOYEES_FILE_REQUEST: 'GET_EMPLOYEES_FILE_REQUEST',
    GET_EMPLOYEES_FILE_SUCCESS: 'GET_EMPLOYEES_FILE_SUCCESS',
    GET_EMPLOYEES_FILE_FAILURE: 'GET_EMPLOYEES_FILE_FAILURE',

    // mgm
    MGM_RESET: 'MGM_RESET',

    MGM_CODE_REQUEST: 'MGM_CODE_REQUEST',
    MGM_CODE_SUCCESS: 'MGM_CODE_SUCCESS',
    MGM_CODE_FAILURE: 'MGM_CODE_FAILURE',

    MGM_SMS_REQUEST: 'MGM_SMS_REQUEST',
    MGM_SMS_SUCCESS: 'MGM_SMS_SUCCESS',
    MGM_SMS_FAILURE: 'MGM_SMS_FAILURE',

    INVITED_USERS_REQUEST: 'INVITED_USERS_REQUEST',
    INVITED_USERS_SUCCESS: 'INVITED_USERS_SUCCESS',
    INVITED_USERS_FAILURE: 'INVITED_USERS_FAILURE',

    USER_INVITED_REQUEST: 'USER_INVITED_REQUEST',
    USER_INVITED_SUCCESS: 'USER_INVITED_SUCCESS',
    USER_INVITED_FAILURE: 'USER_INVITED_FAILURE',
};

export default ACTIONSNAME;
