const teams = [
    { label: 'ABC', value: 'ABC' },
    { label: 'Afogados', value: 'Afogados' },
    { label: 'África do Sul', value: 'África do Sul' },
    { label: 'Água Santa', value: 'Água Santa' },
    { label: 'Águia de Marabá', value: 'Águia de Marabá' },
    { label: 'Águia Negra', value: 'Águia Negra' },
    { label: 'Aimoré', value: 'Aimoré' },
    { label: 'Ajax', value: 'Ajax' },
    { label: 'Albânia', value: 'Albânia' },
    { label: 'Alecrim', value: 'Alecrim' },
    { label: 'Alemanha', value: 'Alemanha' },
    { label: 'Almirante Barroso', value: 'Almirante Barroso' },
    { label: 'Alto Acre', value: 'Alto Acre' },
    { label: 'Alto Santo', value: 'Alto Santo' },
    { label: 'Altos', value: 'Altos' },
    { label: 'Amadense', value: 'Amadense' },
    { label: 'Amax', value: 'Amax' },
    { label: 'América de Três Rios', value: 'América de Três Rios' },
    { label: 'América TO', value: 'América TO' },
    { label: 'América - MG', value: 'América - MG' },
    { label: 'América - PE', value: 'América - PE' },
    { label: 'America - RJ', value: 'America - RJ' },
    { label: 'América - RN', value: 'América - RN' },
    { label: 'América - SE', value: 'América - SE' },
    { label: 'América - SP', value: 'América - SP' },
    { label: 'Americano - MA', value: 'Americano - MA' },
    { label: 'Americano - RJ', value: 'Americano - RJ' },
    { label: 'Anapolina', value: 'Anapolina' },
    { label: 'Anápolis', value: 'Anápolis' },
    { label: 'Andirá', value: 'Andirá' },
    { label: 'Angra dos Reis', value: 'Angra dos Reis' },
    { label: 'Aparecidense', value: 'Aparecidense' },
    { label: 'Aquidauanense', value: 'Aquidauanense' },
    { label: 'Araçatuba', value: 'Araçatuba' },
    { label: 'Aracruz', value: 'Aracruz' },
    { label: 'Araguaia', value: 'Araguaia' },
    { label: 'Araguaína', value: 'Araguaína' },
    { label: 'Araioses', value: 'Araioses' },
    { label: 'Arapongas', value: 'Arapongas' },
    { label: 'Araripina', value: 'Araripina' },
    { label: 'Araxá', value: 'Araxá' },
    { label: 'Argélia', value: 'Argélia' },
    { label: 'Argentina', value: 'Argentina' },
    { label: 'Ariquemes', value: 'Ariquemes' },
    { label: 'Arraial do Cabo', value: 'Arraial do Cabo' },
    { label: 'Arsenal', value: 'Arsenal' },
    { label: 'Asa', value: 'Asa' },
    { label: 'Assisense', value: 'Assisense' },
    { label: 'Assu', value: 'Assu' },
    { label: 'Aston Villa', value: 'Aston Villa' },
    { label: 'Atalanta', value: 'Atalanta' },
    { label: 'Athletic Bilbao', value: 'Athletic Bilbao' },
    { label: 'Atibaia', value: 'Atibaia' },
    { label: 'Atlântico', value: 'Atlântico' },
    { label: 'Atlético Araçatuba', value: 'Atlético Araçatuba' },
    { label: 'Atlético de Madrid', value: 'Atlético de Madrid' },
    { label: 'Atlético Ibirama', value: 'Atlético Ibirama' },
    { label: 'Atlético Mogi', value: 'Atlético Mogi' },
    { label: 'Atlético Roraima', value: 'Atlético Roraima' },
    { label: 'Atlético Sorocaba', value: 'Atlético Sorocaba' },
    { label: 'Atlético - AC', value: 'Atlético - AC' },
    { label: 'Atlético - BA', value: 'Atlético - BA' },
    { label: 'Atlético - ES', value: 'Atlético - ES' },
    { label: 'Atlético - GO', value: 'Atlético - GO' },
    { label: 'Atlético - MG', value: 'Atlético - MG' },
    { label: 'Atlético - PB', value: 'Atlético - PB' },
    { label: 'Atlético - PE', value: 'Atlético - PE' },
    { label: 'Atlético - PR', value: 'Atlético - PR' },
    { label: 'Audax - RJ', value: 'Audax - RJ' },
    { label: 'Audax - SP', value: 'Audax - SP' },
    { label: 'Austrália', value: 'Austrália' },
    { label: 'Áustria', value: 'Áustria' },
    { label: 'Auto Esporte - PB', value: 'Auto Esporte - PB' },
    { label: 'Avaí', value: 'Avaí' },
    { label: 'Avenida', value: 'Avenida' },
    { label: 'Bacabal', value: 'Bacabal' },
    { label: 'Bahia', value: 'Bahia' },
    { label: 'Bahia de Feira', value: 'Bahia de Feira' },
    { label: 'Balsas', value: 'Balsas' },
    { label: 'Bandeirante', value: 'Bandeirante' },
    { label: 'Bandeirante - SP', value: 'Bandeirante - SP' },
    { label: 'Bangu', value: 'Bangu' },
    { label: 'Baraúnas', value: 'Baraúnas' },
    { label: 'Barcelona', value: 'Barcelona' },
    { label: 'Barcelona - RO', value: 'Barcelona - RO' },
    { label: 'Baré', value: 'Baré' },
    { label: 'Barra Mansa', value: 'Barra Mansa' },
    { label: 'Barras', value: 'Barras' },
    { label: 'Barueri', value: 'Barueri' },
    { label: 'Bayern de Munique', value: 'Bayern de Munique' },
    { label: 'Bélgica', value: 'Bélgica' },
    { label: 'Belo Jardim', value: 'Belo Jardim' },
    { label: 'Benfica', value: 'Benfica' },
    { label: 'Betis', value: 'Betis' },
    { label: 'Boa Esporte', value: 'Boa Esporte' },
    { label: 'Boavista', value: 'Boavista' },
    { label: 'Boca Júnior', value: 'Boca Júnior' },
    { label: 'Bolívia', value: 'Bolívia' },
    { label: 'Bologna', value: 'Bologna' },
    { label: 'Bonsucesso', value: 'Bonsucesso' },
    { label: 'Boquinhense', value: 'Boquinhense' },
    { label: 'Borussia Dortmund', value: 'Borussia Dortmund' },
    { label: 'Bósnia', value: 'Bósnia' },
    { label: 'Botafogo', value: 'Botafogo' },
    { label: 'Botafogo - BA', value: 'Botafogo - BA' },
    { label: 'Botafogo - DF', value: 'Botafogo - DF' },
    { label: 'Botafogo - PB', value: 'Botafogo - PB' },
    { label: 'Botafogo - se', value: 'Botafogo - se' },
    { label: 'Botafogo - sp', value: 'Botafogo - sp' },
    { label: 'Bragantino', value: 'Bragantino' },
    { label: 'Brasil', value: 'Brasil' },
    { label: 'Brasil de Pelotas', value: 'Brasil de Pelotas' },
    { label: 'Brasília', value: 'Brasília' },
    { label: 'Brasiliense', value: 'Brasiliense' },
    { label: 'Brazlândia', value: 'Brazlândia' },
    { label: 'Brusque', value: 'Brusque' },
    { label: 'Cabofriense', value: 'Cabofriense' },
    { label: 'Cacerense', value: 'Cacerense' },
    { label: 'Cachoeiro', value: 'Cachoeiro' },
    { label: 'Cagliari', value: 'Cagliari' },
    { label: 'Caiçara', value: 'Caiçara' },
    { label: 'Caldas Novas', value: 'Caldas Novas' },
    { label: 'Caldense', value: 'Caldense' },
    { label: 'Camaçari', value: 'Camaçari' },
    { label: 'Camarões', value: 'Camarões' },
    { label: 'Camboriú', value: 'Camboriú' },
    { label: 'Cametá', value: 'Cametá' },
    { label: 'Campinense', value: 'Campinense' },
    { label: 'Campos', value: 'Campos' },
    { label: 'Canindé', value: 'Canindé' },
    { label: 'Canoas', value: 'Canoas' },
    { label: 'Capital', value: 'Capital' },
    { label: 'Capital FC', value: 'Capital FC' },
    { label: 'Capivariano', value: 'Capivariano' },
    { label: 'Capixaba', value: 'Capixaba' },
    { label: 'Carajás', value: 'Carajás' },
    { label: 'Castanhal', value: 'Castanhal' },
    { label: 'Castelo', value: 'Castelo' },
    { label: 'Catanduvense', value: 'Catanduvense' },
    { label: 'Catania', value: 'Catania' },
    { label: 'Catuense', value: 'Catuense' },
    { label: 'Caxias', value: 'Caxias' },
    { label: 'Ceará', value: 'Ceará' },
    { label: 'Ceilandense', value: 'Ceilandense' },
    { label: 'Ceilândia', value: 'Ceilândia' },
    { label: 'Celta de Vigo', value: 'Celta de Vigo' },
    { label: 'Cene', value: 'Cene' },
    { label: 'Central', value: 'Central' },
    { label: 'Ceo', value: 'Ceo' },
    { label: 'Cerâmica', value: 'Cerâmica' },
    { label: 'Chã Grande', value: 'Chã Grande' },
    { label: 'Chapecoense', value: 'Chapecoense' },
    { label: 'Chelsea', value: 'Chelsea' },
    { label: 'Chievo', value: 'Chievo' },
    { label: 'Chile', value: 'Chile' },
    { label: 'Cianorte', value: 'Cianorte' },
    { label: 'Colatina', value: 'Colatina' },
    { label: 'Colinas', value: 'Colinas' },
    { label: 'Colo Colo-BA', value: 'Colo Colo-BA' },
    { label: 'Colômbia', value: 'Colômbia' },
    { label: 'Comercial - AL', value: 'Comercial - AL' },
    { label: 'Comercial - MS', value: 'Comercial - MS' },
    { label: 'Comercial - PI', value: 'Comercial - PI' },
    { label: 'Comercial - SP', value: 'Comercial - SP' },
    { label: 'Confiança', value: 'Confiança' },
    { label: 'Conilon', value: 'Conilon' },
    { label: 'Cordino', value: 'Cordino' },
    { label: 'Coreia do Norte', value: 'Coreia do Norte' },
    { label: 'Coreia do Sul', value: 'Coreia do Sul' },
    { label: 'Cori-Sabbá', value: 'Cori-Sabbá' },
    { label: 'Corinthians', value: 'Corinthians' },
    { label: 'Corintians - RN', value: 'Corintians - RN' },
    { label: 'Coritiba', value: 'Coritiba' },
    { label: 'Coritiba - SE', value: 'Coritiba - SE' },
    { label: 'Corumbaense', value: 'Corumbaense' },
    { label: 'Coruripe', value: 'Coruripe' },
    { label: 'Costa do Marfim', value: 'Costa do Marfim' },
    { label: 'Costa Rica', value: 'Costa Rica' },
    { label: 'Costa Rica - MS', value: 'Costa Rica - MS' },
    { label: 'Crac', value: 'Crac' },
    { label: 'Crateús', value: 'Crateús' },
    { label: 'Crato', value: 'Crato' },
    { label: 'Crb', value: 'Crb' },
    { label: 'Criciúma', value: 'Criciúma' },
    { label: 'Croácia', value: 'Croácia' },
    { label: 'Cruzeiro', value: 'Cruzeiro' },
    { label: 'Cruzeiro - DF', value: 'Cruzeiro - DF' },
    { label: 'Cruzeiro - PB', value: 'Cruzeiro - PB' },
    { label: 'Cruzeiro - RS', value: 'Cruzeiro - RS' },
    { label: 'Csa', value: 'Csa' },
    { label: 'Cse', value: 'Cse' },
    { label: 'Csp', value: 'Csp' },
    { label: 'Cuiabá', value: 'Cuiabá' },
    { label: 'Democrata GV', value: 'Democrata GV' },
    { label: 'Deportivo la Coruña', value: 'Deportivo la Coruña' },
    { label: 'Desportiva Ferroviária', value: 'Desportiva Ferroviária' },
    { label: 'Desportiva Paraense', value: 'Desportiva Paraense' },
    { label: 'Desportivo Brasil', value: 'Desportivo Brasil' },
    { label: 'Dinamarca', value: 'Dinamarca' },
    { label: 'Dom Bosco', value: 'Dom Bosco' },
    { label: 'Dorense', value: 'Dorense' },
    { label: 'Doze', value: 'Doze' },
    { label: 'Duque de Caxias', value: 'Duque de Caxias' },
    { label: 'Ecus', value: 'Ecus' },
    { label: 'Elosport', value: 'Elosport' },
    { label: 'Equador', value: 'Equador' },
    { label: 'Eslováquia', value: 'Eslováquia' },
    { label: 'Eslovênia', value: 'Eslovênia' },
    { label: 'Espanha', value: 'Espanha' },
    { label: 'Espanyol', value: 'Espanyol' },
    { label: 'Espigão', value: 'Espigão' },
    { label: 'Espírito Santo', value: 'Espírito Santo' },
    { label: 'Esporte de Patos', value: 'Esporte de Patos' },
    { label: 'Esportivo', value: 'Esportivo' },
    { label: 'Esse', value: 'Esse' },
    { label: 'Estados Unidos', value: 'Estados Unidos' },
    { label: 'Estanciano', value: 'Estanciano' },
    { label: 'Estrela do Norte', value: 'Estrela do Norte' },
    { label: 'Everton', value: 'Everton' },
    { label: 'Expressinho', value: 'Expressinho' },
    { label: 'Fast', value: 'Fast' },
    { label: 'FC Cascavel', value: 'FC Cascavel' },
    { label: 'Feirense', value: 'Feirense' },
    { label: 'Fernandópolis', value: 'Fernandópolis' },
    { label: 'Ferroviária', value: 'Ferroviária' },
    { label: 'Ferroviário', value: 'Ferroviário' },
    { label: 'Figueirense', value: 'Figueirense' },
    { label: 'Fiorentina', value: 'Fiorentina' },
    { label: 'Flamengo', value: 'Flamengo' },
    { label: 'Flamengo de Arcoverde', value: 'Flamengo de Arcoverde' },
    { label: 'Flamengo de Guanambi', value: 'Flamengo de Guanambi' },
    { label: 'Flamengo - PB', value: 'Flamengo - PB' },
    { label: 'Flamengo - PI', value: 'Flamengo - PI' },
    { label: 'Flu de Feira', value: 'Flu de Feira' },
    { label: 'Fluminense', value: 'Fluminense' },
    { label: 'Força e Luz', value: 'Força e Luz' },
    { label: 'Formosa', value: 'Formosa' },
    { label: 'Fortaleza', value: 'Fortaleza' },
    { label: 'Foz do Iguaçu', value: 'Foz do Iguaçu' },
    { label: 'França', value: 'França' },
    { label: 'Francana', value: 'Francana' },
    { label: 'Frei Paulistano', value: 'Frei Paulistano' },
    { label: 'Friburguense', value: 'Friburguense' },
    { label: 'Fulham', value: 'Fulham' },
    { label: 'Funorte', value: 'Funorte' },
    { label: 'Galícia', value: 'Galícia' },
    { label: 'Galvez', value: 'Galvez' },
    { label: 'Gama', value: 'Gama' },
    { label: 'Gana', value: 'Gana' },
    { label: 'Gas', value: 'Gas' },
    { label: 'Gavião', value: 'Gavião' },
    { label: 'Gel', value: 'Gel' },
    { label: 'Genoa', value: 'Genoa' },
    { label: 'Genus', value: 'Genus' },
    { label: 'Getafe', value: 'Getafe' },
    { label: 'Globo FC', value: 'Globo FC' },
    { label: 'Glória', value: 'Glória' },
    { label: 'Goianésia', value: 'Goianésia' },
    { label: 'Goiás', value: 'Goiás' },
    { label: 'Goytacaz', value: 'Goytacaz' },
    { label: 'Granada', value: 'Granada' },
    { label: 'Grécia', value: 'Grécia' },
    { label: 'Grêmio', value: 'Grêmio' },
    { label: 'Grêmio Anápolis', value: 'Grêmio Anápolis' },
    { label: 'Grêmio Prudente', value: 'Grêmio Prudente' },
    { label: 'Guajará', value: 'Guajará' },
    { label: 'Guaraí', value: 'Guaraí' },
    { label: 'Guarani', value: 'Guarani' },
    { label: 'Guarani de Juazeiro', value: 'Guarani de Juazeiro' },
    { label: 'Guarani de Palhoça', value: 'Guarani de Palhoça' },
    { label: 'Guarani - MG', value: 'Guarani - MG' },
    { label: 'Guarany de Sobral', value: 'Guarany de Sobral' },
    { label: 'Guarany - SE', value: 'Guarany - SE' },
    { label: 'Guaratinguetá', value: 'Guaratinguetá' },
    { label: 'Guarujá', value: 'Guarujá' },
    { label: 'Gurupi', value: 'Gurupi' },
    { label: 'Haiti', value: 'Haiti' },
    { label: 'Holanda', value: 'Holanda' },
    { label: 'Holanda - AM', value: 'Holanda - AM' },
    { label: 'Honduras', value: 'Honduras' },
    { label: 'Horizonte', value: 'Horizonte' },
    { label: 'Humaitá', value: 'Humaitá' },
    { label: 'Hungria', value: 'Hungria' },
    { label: 'Icasa', value: 'Icasa' },
    { label: 'Imperatriz', value: 'Imperatriz' },
    { label: 'Imperial', value: 'Imperial' },
    { label: 'Independente - AP', value: 'Independente - AP' },
    { label: 'Independente - PA', value: 'Independente - PA' },
    { label: 'Independente - SP', value: 'Independente - SP' },
    { label: 'Inglaterra', value: 'Inglaterra' },
    { label: 'Inter de Lages', value: 'Inter de Lages' },
    { label: 'Inter de Limeira', value: 'Inter de Limeira' },
    { label: 'Internacional', value: 'Internacional' },
    { label: 'Internacional - PB', value: 'Internacional - PB' },
    { label: 'Internazionale', value: 'Internazionale' },
    { label: 'Interporto', value: 'Interporto' },
    { label: 'Ipanema', value: 'Ipanema' },
    { label: 'Ipatinga', value: 'Ipatinga' },
    { label: 'Iporá', value: 'Iporá' },
    { label: 'Irã', value: 'Irã' },
    { label: 'Iranduba', value: 'Iranduba' },
    { label: 'Iraty', value: 'Iraty' },
    { label: 'Irlanda', value: 'Irlanda' },
    { label: 'Irlanda do Norte', value: 'Irlanda do Norte' },
    { label: 'Islândia', value: 'Islândia' },
    { label: 'Itabaiana', value: 'Itabaiana' },
    { label: 'Itabuna', value: 'Itabuna' },
    { label: 'Itália', value: 'Itália' },
    { label: 'Itapajé', value: 'Itapajé' },
    { label: 'Itapipoca', value: 'Itapipoca' },
    { label: 'Itapirense', value: 'Itapirense' },
    { label: 'Itaporã', value: 'Itaporã' },
    { label: 'Ituano', value: 'Ituano' },
    { label: 'Itumbiara', value: 'Itumbiara' },
    { label: 'Ivinhema', value: 'Ivinhema' },
    { label: 'Jabaquara', value: 'Jabaquara' },
    { label: 'Jacobina', value: 'Jacobina' },
    { label: 'Jacuipense', value: 'Jacuipense' },
    { label: 'Jamaica', value: 'Jamaica' },
    { label: 'Japão', value: 'Japão' },
    { label: 'Ji-Paraná', value: 'Ji-Paraná' },
    { label: 'Jmalucelli', value: 'Jmalucelli' },
    { label: 'Joinville', value: 'Joinville' },
    { label: 'José Bonifácio', value: 'José Bonifácio' },
    { label: 'Juazeirense', value: 'Juazeirense' },
    { label: 'Juazeiro', value: 'Juazeiro' },
    { label: 'Juventude', value: 'Juventude' },
    { label: 'Juventus', value: 'Juventus' },
    { label: 'Juventus - AC', value: 'Juventus - AC' },
    { label: 'Juventus - SC', value: 'Juventus - SC' },
    { label: 'Juventus - SP', value: 'Juventus - SP' },
    { label: 'Lagarto', value: 'Lagarto' },
    { label: 'Lajeadense', value: 'Lajeadense' },
    { label: 'Lazio', value: 'Lazio' },
    { label: 'Legião', value: 'Legião' },
    { label: 'Levante', value: 'Levante' },
    { label: 'Linense', value: 'Linense' },
    { label: 'Linhares', value: 'Linhares' },
    { label: 'Liverpool', value: 'Liverpool' },
    { label: 'Londrina', value: 'Londrina' },
    { label: 'Lucena', value: 'Lucena' },
    { label: 'Luverdense', value: 'Luverdense' },
    { label: 'Luziânia', value: 'Luziânia' },
    { label: 'Macaé', value: 'Macaé' },
    { label: 'Macapá', value: 'Macapá' },
    { label: 'Madureira', value: 'Madureira' },
    { label: 'Málaga', value: 'Málaga' },
    { label: 'Mallorca', value: 'Mallorca' },
    { label: 'Mamoré', value: 'Mamoré' },
    { label: 'Manaus', value: 'Manaus' },
    { label: 'Manchester City', value: 'Manchester City' },
    { label: 'Manchester United', value: 'Manchester United' },
    { label: 'Manthiqueira', value: 'Manthiqueira' },
    { label: 'Maracaju', value: 'Maracaju' },
    { label: 'Maracanã', value: 'Maracanã' },
    { label: 'Maranguape', value: 'Maranguape' },
    { label: 'Maranhão', value: 'Maranhão' },
    { label: 'Marcílio Dias', value: 'Marcílio Dias' },
    { label: 'Marília', value: 'Marília' },
    { label: 'Maringá', value: 'Maringá' },
    { label: 'Mato Grosso', value: 'Mato Grosso' },
    { label: 'Mazagão', value: 'Mazagão' },
    { label: 'Metropolitano', value: 'Metropolitano' },
    { label: 'México', value: 'México' },
    { label: 'Miguelense', value: 'Miguelense' },
    { label: 'Milan', value: 'Milan' },
    { label: 'Minas Boca', value: 'Minas Boca' },
    { label: 'Miramar', value: 'Miramar' },
    { label: 'Mirassol', value: 'Mirassol' },
    { label: 'Misto', value: 'Misto' },
    { label: 'Mixto', value: 'Mixto' },
    { label: 'Mogi Mirim', value: 'Mogi Mirim' },
    { label: 'Monte Azul', value: 'Monte Azul' },
    { label: 'Montes Claros', value: 'Montes Claros' },
    { label: 'Morrinhos', value: 'Morrinhos' },
    { label: 'Morumbi', value: 'Morumbi' },
    { label: 'Moto Club', value: 'Moto Club' },
    { label: 'Moto Clube - RO', value: 'Moto Clube - RO' },
    { label: 'Murici', value: 'Murici' },
    { label: 'Nacional Borbense', value: 'Nacional Borbense' },
    { label: 'Nacional de Muriaé', value: 'Nacional de Muriaé' },
    { label: 'Nacional de Patos', value: 'Nacional de Patos' },
    { label: 'Nacional - AM', value: 'Nacional - AM' },
    { label: 'Nacional - PR', value: 'Nacional - PR' },
    { label: 'Napoli', value: 'Napoli' },
    { label: 'Náuas', value: 'Náuas' },
    { label: 'Náutico', value: 'Náutico' },
    { label: 'Náutico - RR', value: 'Náutico - RR' },
    { label: 'Naviraiense', value: 'Naviraiense' },
    { label: 'Newcastle', value: 'Newcastle' },
    { label: 'Nigéria', value: 'Nigéria' },
    { label: 'Noroeste', value: 'Noroeste' },
    { label: 'Norwich City', value: 'Norwich City' },
    { label: 'Nova Iguaçu', value: 'Nova Iguaçu' },
    { label: 'Nova Zelândia', value: 'Nova Zelândia' },
    { label: 'Novo', value: 'Novo' },
    { label: 'Novo Hamburgo', value: 'Novo Hamburgo' },
    { label: 'Novorizontino', value: 'Novorizontino' },
    { label: 'Oeste', value: 'Oeste' },
    { label: 'Olaria', value: 'Olaria' },
    { label: 'Olímpia - SP', value: 'Olímpia - SP' },
    { label: 'Olímpico', value: 'Olímpico' },
    { label: 'Operário FC', value: 'Operário FC' },
    { label: 'Operário VG', value: 'Operário VG' },
    { label: 'Operário - AM', value: 'Operário - AM' },
    { label: 'Operário - MS', value: 'Operário - MS' },
    { label: 'Operário - PR', value: 'Operário - PR' },
    { label: 'Oratório', value: 'Oratório' },
    { label: 'Osasuna', value: 'Osasuna' },
    { label: 'Osvaldo Cruz', value: 'Osvaldo Cruz' },
    { label: 'Paduano', value: 'Paduano' },
    { label: 'País de Gales', value: 'País de Gales' },
    { label: 'Palermo', value: 'Palermo' },
    { label: 'Palmas', value: 'Palmas' },
    { label: 'Palmeira - RN', value: 'Palmeira - RN' },
    { label: 'Palmeiras', value: 'Palmeiras' },
    { label: 'Panamá', value: 'Panamá' },
    { label: 'Paracatu', value: 'Paracatu' },
    { label: 'Paragominas', value: 'Paragominas' },
    { label: 'Paraguai', value: 'Paraguai' },
    { label: 'Paraíba', value: 'Paraíba' },
    { label: 'Paraíso', value: 'Paraíso' },
    { label: 'Paraná', value: 'Paraná' },
    { label: 'Paranavaí', value: 'Paranavaí' },
    { label: 'Paranoá', value: 'Paranoá' },
    { label: 'Parauapebas', value: 'Parauapebas' },
    { label: 'Paris Saint-Germain', value: 'Paris Saint-Germain' },
    { label: 'Parma', value: 'Parma' },
    { label: 'Parnahyba', value: 'Parnahyba' },
    { label: 'Passo Fundo', value: 'Passo Fundo' },
    { label: 'Paulista', value: 'Paulista' },
    { label: 'Paysandu', value: 'Paysandu' },
    { label: 'Pedreira', value: 'Pedreira' },
    { label: 'Pelotas', value: 'Pelotas' },
    { label: 'Penapolense', value: 'Penapolense' },
    { label: 'Penarol - AM', value: 'Penarol - AM' },
    { label: 'Penedense', value: 'Penedense' },
    { label: 'Peru', value: 'Peru' },
    { label: 'Pescara', value: 'Pescara' },
    { label: 'Pesqueira', value: 'Pesqueira' },
    { label: 'Petrolina', value: 'Petrolina' },
    { label: 'Piauí', value: 'Piauí' },
    { label: 'Picos', value: 'Picos' },
    { label: 'Pimentense', value: 'Pimentense' },
    { label: 'Pinheirense', value: 'Pinheirense' },
    { label: 'Plácido de Castro', value: 'Plácido de Castro' },
    { label: 'Planaltina', value: 'Planaltina' },
    { label: 'Poconé', value: 'Poconé' },
    { label: 'Polônia', value: 'Polônia' },
    { label: 'Ponte Preta', value: 'Ponte Preta' },
    { label: 'Porto', value: 'Porto' },
    { label: 'Porto - PE', value: 'Porto - PE' },
    { label: 'Portugal', value: 'Portugal' },
    { label: 'Portuguesa', value: 'Portuguesa' },
    { label: 'Portuguesa Santista', value: 'Portuguesa Santista' },
    { label: 'Portuguesa - RJ', value: 'Portuguesa - RJ' },
    { label: 'Potiguar de Mossoró', value: 'Potiguar de Mossoró' },
    { label: 'Potyguar CN', value: 'Potyguar CN' },
    { label: 'Presidente Prudente', value: 'Presidente Prudente' },
    { label: 'Princesa do Solimões', value: 'Princesa do Solimões' },
    { label: 'Prudentópolis', value: 'Prudentópolis' },
    { label: 'Pstc', value: 'Pstc' },
    { label: 'Psv Eindhoven', value: 'Psv Eindhoven' },
    { label: 'Queens Park Rangers', value: 'Queens Park Rangers' },
    { label: 'Queimadense', value: 'Queimadense' },
    { label: 'Quissamã', value: 'Quissamã' },
    { label: 'Quixadá', value: 'Quixadá' },
    { label: 'Rayo Vallecano', value: 'Rayo Vallecano' },
    { label: 'Rb Brasil', value: 'Rb Brasil' },
    { label: 'Reading', value: 'Reading' },
    { label: 'Real Cubatense', value: 'Real Cubatense' },
    { label: 'Real Desportivo', value: 'Real Desportivo' },
    { label: 'Real Madrid', value: 'Real Madrid' },
    { label: 'Real Noroeste', value: 'Real Noroeste' },
    { label: 'Real Sociedad', value: 'Real Sociedad' },
    { label: 'Real - DF', value: 'Real - DF' },
    { label: 'Real - RR', value: 'Real - RR' },
    { label: 'Remo', value: 'Remo' },
    { label: 'República Tcheca', value: 'República Tcheca' },
    { label: 'Resende', value: 'Resende' },
    { label: 'Ricanato', value: 'Ricanato' },
    { label: 'Rio Branco VN', value: 'Rio Branco VN' },
    { label: 'Rio Branco - AC', value: 'Rio Branco - AC' },
    { label: 'Rio Branco - ES', value: 'Rio Branco - ES' },
    { label: 'Rio Branco - PR', value: 'Rio Branco - PR' },
    { label: 'Rio Branco - RJ', value: 'Rio Branco - RJ' },
    { label: 'Rio Branco - SP', value: 'Rio Branco - SP' },
    { label: 'Rio Claro', value: 'Rio Claro' },
    { label: 'Rio Negro - AM', value: 'Rio Negro - AM' },
    { label: 'Rio Negro - RR', value: 'Rio Negro - RR' },
    { label: 'Rio Preto', value: 'Rio Preto' },
    { label: 'Rio Verde - GO', value: 'Rio Verde - GO' },
    { label: 'Riostrense', value: 'Riostrense' },
    { label: 'River Plate - SE', value: 'River Plate - SE' },
    { label: 'River - PI', value: 'River - PI' },
    { label: 'Rolim de Moura', value: 'Rolim de Moura' },
    { label: 'Roma', value: 'Roma' },
    { label: 'Roma - PR', value: 'Roma - PR' },
    { label: 'Romênia', value: 'Romênia' },
    { label: 'Rondoniense', value: 'Rondoniense' },
    { label: 'Rondonópolis', value: 'Rondonópolis' },
    { label: 'Rubro', value: 'Rubro' },
    { label: 'Rússia', value: 'Rússia' },
    { label: 'Sabiá', value: 'Sabiá' },
    { label: 'Salgueiro', value: 'Salgueiro' },
    { label: 'Sampaio Corrêa', value: 'Sampaio Corrêa' },
    { label: 'Sampaio Corrêa - RJ', value: 'Sampaio Corrêa - RJ' },
    { label: 'Sampdoria', value: 'Sampdoria' },
    { label: 'Santa Cruz', value: 'Santa Cruz' },
    { label: 'Santa Cruz de Natal', value: 'Santa Cruz de Natal' },
    { label: 'Santa Cruz - PA', value: 'Santa Cruz - PA' },
    { label: 'Santa Cruz - PB', value: 'Santa Cruz - PB' },
    { label: 'Santa Cruz - RN', value: 'Santa Cruz - RN' },
    { label: 'Santa Cruz - RS', value: 'Santa Cruz - RS' },
    { label: 'Santa Maria', value: 'Santa Maria' },
    { label: 'Santa Quitéria', value: 'Santa Quitéria' },
    { label: 'Santa Rita', value: 'Santa Rita' },
    { label: 'Santacruzense', value: 'Santacruzense' },
    { label: 'Santana', value: 'Santana' },
    { label: 'Santo André', value: 'Santo André' },
    { label: 'Santos', value: 'Santos' },
    { label: 'Santos - AP', value: 'Santos - AP' },
    { label: 'São Benedito', value: 'São Benedito' },
    { label: 'São Bento', value: 'São Bento' },
    { label: 'São Bernardo', value: 'São Bernardo' },
    { label: 'São Caetano', value: 'São Caetano' },
    { label: 'São Carlos', value: 'São Carlos' },
    { label: 'São Domingos', value: 'São Domingos' },
    { label: 'São Francisco - PA', value: 'São Francisco - PA' },
    { label: 'São João da Barra', value: 'São João da Barra' },
    { label: 'São José dos Campos', value: 'São José dos Campos' },
    { label: 'São José - AP', value: 'São José - AP' },
    { label: 'São José - MA', value: 'São José - MA' },
    { label: 'São José - RS', value: 'São José - RS' },
    { label: 'São José - SP', value: 'São José - SP' },
    { label: 'São Luiz', value: 'São Luiz' },
    { label: 'São Mateus', value: 'São Mateus' },
    { label: 'São Paulo', value: 'São Paulo' },
    { label: 'São Paulo-ap', value: 'São Paulo-ap' },
    { label: 'São Paulo-rs', value: 'São Paulo-rs' },
    { label: 'São Pedro', value: 'São Pedro' },
    { label: 'São Raimundo - AM', value: 'São Raimundo - AM' },
    { label: 'São Raimundo - PA', value: 'São Raimundo - PA' },
    { label: 'São Raimundo - RR', value: 'São Raimundo - RR' },
    { label: 'São Vicente', value: 'São Vicente' },
    { label: 'Serc', value: 'Serc' },
    { label: 'Sergipe', value: 'Sergipe' },
    { label: 'Serra', value: 'Serra' },
    { label: 'Serra Macaense', value: 'Serra Macaense' },
    { label: 'Serra Talhada', value: 'Serra Talhada' },
    { label: 'Serrano - BA', value: 'Serrano - BA' },
    { label: 'Serrano - PB', value: 'Serrano - PB' },
    { label: 'Serrano - RJ', value: 'Serrano - RJ' },
    { label: 'Sérvia', value: 'Sérvia' },
    { label: 'Sete de Dourados', value: 'Sete de Dourados' },
    { label: 'Sete de Junho', value: 'Sete de Junho' },
    { label: 'Sete de Setembro', value: 'Sete de Setembro' },
    { label: 'Sete de Setembro - AL', value: 'Sete de Setembro - AL' },
    { label: 'Sevilla', value: 'Sevilla' },
    { label: 'Shakhtar Donetsk', value: 'Shakhtar Donetsk' },
    { label: 'Siena', value: 'Siena' },
    { label: 'Sinop', value: 'Sinop' },
    { label: 'Sobradinho', value: 'Sobradinho' },
    { label: 'Social', value: 'Social' },
    { label: 'Socorrense', value: 'Socorrense' },
    { label: 'Sorriso', value: 'Sorriso' },
    { label: 'Sousa', value: 'Sousa' },
    { label: 'Southampton', value: 'Southampton' },
    { label: 'Sparta', value: 'Sparta' },
    { label: 'Sport', value: 'Sport' },
    { label: 'Sport Atalaia', value: 'Sport Atalaia' },
    { label: 'Sport Belém', value: 'Sport Belém' },
    { label: 'Sport Campina', value: 'Sport Campina' },
    { label: 'Sport - ES', value: 'Sport - ES' },
    { label: 'Stoke City', value: 'Stoke City' },
    { label: 'Suécia', value: 'Suécia' },
    { label: 'Suíça', value: 'Suíça' },
    { label: 'Sul América', value: 'Sul América' },
    { label: 'Sunderland', value: 'Sunderland' },
    { label: 'Swansea', value: 'Swansea' },
    { label: 'Taiti', value: 'Taiti' },
    { label: 'Tanabi', value: 'Tanabi' },
    { label: 'Tapajós', value: 'Tapajós' },
    { label: 'Tarumã', value: 'Tarumã' },
    { label: 'Taubaté', value: 'Taubaté' },
    { label: 'Teresópolis', value: 'Teresópolis' },
    { label: 'Tigres - RJ', value: 'Tigres - RJ' },
    { label: 'Tiradentes - CE', value: 'Tiradentes - CE' },
    { label: 'Tiradentes - PA', value: 'Tiradentes - PA' },
    { label: 'Tocantinópolis', value: 'Tocantinópolis' },
    { label: 'Tocantins', value: 'Tocantins' },
    { label: 'Tocantins de Palmas', value: 'Tocantins de Palmas' },
    { label: 'Toledo', value: 'Toledo' },
    { label: 'Tombense', value: 'Tombense' },
    { label: 'Torino', value: 'Torino' },
    { label: 'Tottenham', value: 'Tottenham' },
    { label: 'Trairiense', value: 'Trairiense' },
    { label: 'Trem', value: 'Trem' },
    { label: 'Treze', value: 'Treze' },
    { label: 'Tricordiano', value: 'Tricordiano' },
    { label: 'Trindade', value: 'Trindade' },
    { label: 'Tubarão', value: 'Tubarão' },
    { label: 'Tuna Luso', value: 'Tuna Luso' },
    { label: 'Tupã', value: 'Tupã' },
    { label: 'Tupi - MG', value: 'Tupi - MG' },
    { label: 'Tupy - ES', value: 'Tupy - ES' },
    { label: 'Turquia', value: 'Turquia' },
    { label: 'Uberaba', value: 'Uberaba' },
    { label: 'Uberlândia', value: 'Uberlândia' },
    { label: 'Ubiratan', value: 'Ubiratan' },
    { label: 'Ucrânia', value: 'Ucrânia' },
    { label: 'Udinese', value: 'Udinese' },
    { label: 'União ABC', value: 'União ABC' },
    { label: 'União Barbarense', value: 'União Barbarense' },
    { label: 'União Cacoalense', value: 'União Cacoalense' },
    { label: 'União Frederiquense', value: 'União Frederiquense' },
    { label: 'União Mogi', value: 'União Mogi' },
    { label: 'União Rondonópolis', value: 'União Rondonópolis' },
    { label: 'União Suzano', value: 'União Suzano' },
    { label: 'União - AL', value: 'União - AL' },
    { label: 'Uniclinic', value: 'Uniclinic' },
    { label: 'Urso', value: 'Urso' },
    { label: 'Urt', value: 'Urt' },
    { label: 'Uruguai', value: 'Uruguai' },
    { label: 'Valencia', value: 'Valencia' },
    { label: 'Valladolid', value: 'Valladolid' },
    { label: 'Vasco', value: 'Vasco' },
    { label: 'Vasco - AC', value: 'Vasco - AC' },
    { label: 'Velo Clube', value: 'Velo Clube' },
    { label: 'Venezuela', value: 'Venezuela' },
    { label: 'Vênus', value: 'Vênus' },
    { label: 'Vera Cruz', value: 'Vera Cruz' },
    { label: 'Veranópolis', value: 'Veranópolis' },
    { label: 'Viana', value: 'Viana' },
    { label: 'Vila Aurora', value: 'Vila Aurora' },
    { label: 'Vila Nova', value: 'Vila Nova' },
    { label: 'Vila Nova - ES', value: 'Vila Nova - ES' },
    { label: 'Vilavelhense', value: 'Vilavelhense' },
    { label: 'Vilhena', value: 'Vilhena' },
    { label: 'Villa nova - MG', value: 'Villa nova - MG' },
    { label: 'Vitória', value: 'Vitória' },
    { label: 'Vitória da Conquista', value: 'Vitória da Conquista' },
    { label: 'Vitória - ES', value: 'Vitória - ES' },
    { label: 'Vitória - PE', value: 'Vitória - PE' },
    { label: 'Vocem', value: 'Vocem' },
    { label: 'Volta Redonda', value: 'Volta Redonda' },
    { label: 'Votuporanguense', value: 'Votuporanguense' },
    { label: 'Werder Bremen', value: 'Werder Bremen' },
    { label: 'West Bromwich', value: 'West Bromwich' },
    { label: 'West Ham', value: 'West Ham' },
    { label: 'Wigan', value: 'Wigan' },
    { label: 'XV de Jaú', value: 'XV de Jaú' },
    { label: 'XV de Piracicaba', value: 'XV de Piracicaba' },
    { label: 'Ypiranga - AP', value: 'Ypiranga - AP' },
    { label: 'Ypiranga - PE', value: 'Ypiranga - PE' },
    { label: 'Ypiranga - RS', value: 'Ypiranga - RS' },
    { label: 'Zaragoza', value: 'Zaragoza' },
    { label: 'Zenit', value: 'Zenit' },
];

export default teams;
