//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eaiSingleSignOn
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsParticipante", Namespace="http://tempuri.org/")]
    public partial class wsParticipante : object
    {
        
        private string NomeField;
        
        private string CPFField;
        
        private string DataNascimentoField;
        
        private string EmailField;
        
        private string SexoField;
        
        private string CEPField;
        
        private string LogradouroField;
        
        private string NumeroField;
        
        private string ComplementoField;
        
        private string BairroField;
        
        private string CidadeField;
        
        private string UFField;
        
        private string TelefoneField;
        
        private string CelularField;
        
        private string CEP2Field;
        
        private string Logradouro2Field;
        
        private string Numero2Field;
        
        private string Complemento2Field;
        
        private string Bairro2Field;
        
        private string Cidade2Field;
        
        private string UF2Field;
        
        private string Telefone2Field;
        
        private string Celular2Field;
        
        private string CodHierarquiaNivel1Field;
        
        private string CodHierarquiaNivel2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CPF
        {
            get
            {
                return this.CPFField;
            }
            set
            {
                this.CPFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DataNascimento
        {
            get
            {
                return this.DataNascimentoField;
            }
            set
            {
                this.DataNascimentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Sexo
        {
            get
            {
                return this.SexoField;
            }
            set
            {
                this.SexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CEP
        {
            get
            {
                return this.CEPField;
            }
            set
            {
                this.CEPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Logradouro
        {
            get
            {
                return this.LogradouroField;
            }
            set
            {
                this.LogradouroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                this.NumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Complemento
        {
            get
            {
                return this.ComplementoField;
            }
            set
            {
                this.ComplementoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Bairro
        {
            get
            {
                return this.BairroField;
            }
            set
            {
                this.BairroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Cidade
        {
            get
            {
                return this.CidadeField;
            }
            set
            {
                this.CidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string UF
        {
            get
            {
                return this.UFField;
            }
            set
            {
                this.UFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Telefone
        {
            get
            {
                return this.TelefoneField;
            }
            set
            {
                this.TelefoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Celular
        {
            get
            {
                return this.CelularField;
            }
            set
            {
                this.CelularField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string CEP2
        {
            get
            {
                return this.CEP2Field;
            }
            set
            {
                this.CEP2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Logradouro2
        {
            get
            {
                return this.Logradouro2Field;
            }
            set
            {
                this.Logradouro2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Numero2
        {
            get
            {
                return this.Numero2Field;
            }
            set
            {
                this.Numero2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Complemento2
        {
            get
            {
                return this.Complemento2Field;
            }
            set
            {
                this.Complemento2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string Bairro2
        {
            get
            {
                return this.Bairro2Field;
            }
            set
            {
                this.Bairro2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Cidade2
        {
            get
            {
                return this.Cidade2Field;
            }
            set
            {
                this.Cidade2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string UF2
        {
            get
            {
                return this.UF2Field;
            }
            set
            {
                this.UF2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string Telefone2
        {
            get
            {
                return this.Telefone2Field;
            }
            set
            {
                this.Telefone2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string Celular2
        {
            get
            {
                return this.Celular2Field;
            }
            set
            {
                this.Celular2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string CodHierarquiaNivel1
        {
            get
            {
                return this.CodHierarquiaNivel1Field;
            }
            set
            {
                this.CodHierarquiaNivel1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string CodHierarquiaNivel2
        {
            get
            {
                return this.CodHierarquiaNivel2Field;
            }
            set
            {
                this.CodHierarquiaNivel2Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsRetornoAutenticacao", Namespace="http://tempuri.org/")]
    public partial class wsRetornoAutenticacao : object
    {
        
        private bool hasErrorField;
        
        private string messageField;
        
        private string tokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool hasError
        {
            get
            {
                return this.hasErrorField;
            }
            set
            {
                this.hasErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="eaiSingleSignOn.eaiSingleSignOnSoap")]
    public interface eaiSingleSignOnSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Autenticar", ReplyAction="*")]
        System.Threading.Tasks.Task<eaiSingleSignOn.AutenticarResponse> AutenticarAsync(eaiSingleSignOn.AutenticarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Autenticar", Namespace="http://tempuri.org/", Order=0)]
        public eaiSingleSignOn.AutenticarRequestBody Body;
        
        public AutenticarRequest()
        {
        }
        
        public AutenticarRequest(eaiSingleSignOn.AutenticarRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutenticarRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hash;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int campanha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public eaiSingleSignOn.wsParticipante participante;
        
        public AutenticarRequestBody()
        {
        }
        
        public AutenticarRequestBody(string hash, int campanha, eaiSingleSignOn.wsParticipante participante)
        {
            this.hash = hash;
            this.campanha = campanha;
            this.participante = participante;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticarResponse", Namespace="http://tempuri.org/", Order=0)]
        public eaiSingleSignOn.AutenticarResponseBody Body;
        
        public AutenticarResponse()
        {
        }
        
        public AutenticarResponse(eaiSingleSignOn.AutenticarResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutenticarResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public eaiSingleSignOn.wsRetornoAutenticacao AutenticarResult;
        
        public AutenticarResponseBody()
        {
        }
        
        public AutenticarResponseBody(eaiSingleSignOn.wsRetornoAutenticacao AutenticarResult)
        {
            this.AutenticarResult = AutenticarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public interface eaiSingleSignOnSoapChannel : eaiSingleSignOn.eaiSingleSignOnSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public partial class eaiSingleSignOnSoapClient : System.ServiceModel.ClientBase<eaiSingleSignOn.eaiSingleSignOnSoap>, eaiSingleSignOn.eaiSingleSignOnSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public eaiSingleSignOnSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(eaiSingleSignOnSoapClient.GetBindingForEndpoint(endpointConfiguration), eaiSingleSignOnSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public eaiSingleSignOnSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(eaiSingleSignOnSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public eaiSingleSignOnSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(eaiSingleSignOnSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public eaiSingleSignOnSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eaiSingleSignOn.AutenticarResponse> eaiSingleSignOn.eaiSingleSignOnSoap.AutenticarAsync(eaiSingleSignOn.AutenticarRequest request)
        {
            return base.Channel.AutenticarAsync(request);
        }
        
        public System.Threading.Tasks.Task<eaiSingleSignOn.AutenticarResponse> AutenticarAsync(string hash, int campanha, eaiSingleSignOn.wsParticipante participante)
        {
            eaiSingleSignOn.AutenticarRequest inValue = new eaiSingleSignOn.AutenticarRequest();
            inValue.Body = new eaiSingleSignOn.AutenticarRequestBody();
            inValue.Body.hash = hash;
            inValue.Body.campanha = campanha;
            inValue.Body.participante = participante;
            return ((eaiSingleSignOn.eaiSingleSignOnSoap)(this)).AutenticarAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.eaiSingleSignOnSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.eaiSingleSignOnSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.eaiSingleSignOnSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.eaipremiospp.com.br/eaiSingleSignOn.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.eaiSingleSignOnSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.eaipremiospp.com.br/eaiSingleSignOn.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            eaiSingleSignOnSoap,
            
            eaiSingleSignOnSoap12,
        }
    }
}
